Title:
  leaves that are green
FileName:
  leaves-that-are-green
Description:
  Took this pic on my way to university just by Lake Michigan
PubDate:
  2021-10-28
Tags:
  - Name: photos
  - Name: milwaukee
  - Name: english
Thumbnail:
  Src: https://preview.redd.it/rgy06570s4w71.jpg?width=1024&auto=webp&v=enabled&s=6976a979db46bb48fa96e6fe61dcc6d1d2395141
  Alt: photo of tops of trees becoming orange
  Title: "'I was twenty-one years when I wrote this song'"
