Title:
  a frosty stroll
FileName:
  a-frosty-stroll
Description:
  I was walking over a bridge when I took this photo of this cool looking street. I didn't notice the woman right away.
PubDate:
  2022-01-31
Tags:
  - Name: photos
  - Name: milwaukee
  - Name: english
Thumbnail:
  Src: /static/img/posts/a-frosty-stroll/a_frosty_stroll.webp
  Alt: photo of a woman walking beside a bright, cold street
