Title:
  y = ln(x)
FileName:
  natural-log
Description:
  Went to a weird park with my roommate and took this pic of a branch there
PubDate:
  2021-11-21
Tags:
  - Name: photos
  - Name: english
Thumbnail:
  Src: https://preview.redd.it/rgy06570s4w71.jpg?width=1024&auto=webp&v=enabled&s=6976a979db46bb48fa96e6fe61dcc6d1d2395141
  Alt: photo of bare, dead branch in front of goo pond
  Title: ln(e^a) = a
