Title:
  new site... again
FileName:
  new-site-again
Description:
  Justifying why I spent two months remaking my site as a cover to learn go.
PubDate:
  2023-08-06
Tags:
  - Name: technology
  - Name: english
  - Name: articles
